import type { ExperienceItem } from "@/types";

export const experienceContent: ExperienceItem[] = [
  {
    role: "Associate Software Engineer (ML)",
    company: "Kaz Software",
    location: "Dhaka, Bangladesh",
    period: "Jan 2025 – Present",
    employmentType: "Full-time",
    current: true,
    highlights: [
      "Built custom ML document classification replacing managed cloud OCR, cutting infrastructure costs by 70–90% while maintaining ~95% accuracy.",
      "Designed serverless document processing pipelines on AWS Step Functions for scalable, fault-tolerant execution.",
      "Shipped configurable LLM-based extraction with dynamic model selection per workflow and .NET services for orchestration and failure handling.",
      "Developed agentic RAG systems for high-volume regulatory content, reducing manual monitoring effort by 89%.",
      "Delivered production multilabel classification with semantic chunking, improving accuracy by 48% and lowering monthly review overhead.",
    ],
    technologies: [
      "Python",
      "C#",
      ".NET",
      "AWS Lambda",
      "Step Functions",
      "Bedrock",
      "FastAPI",
      "LangChain",
      "DynamoDB",
      "Docker",
      "Redis",
      "Celery",
      "RAG",
      "LLMs",
    ],
  },
  {
    role: "AI Developer",
    company: "Sasthotech",
    location: "Rajshahi, Bangladesh",
    period: "Nov 2023 – Dec 2024",
    employmentType: "Full-time",
    highlights: [
      "Designed a vision-language pipeline for automated chest X-ray report generation with containerized models on serverless production APIs.",
      "Built AWS EC2 and Nginx backend infrastructure for scalable model hosting.",
      "Engineered data pipelines to structure doctor and hospital information as a knowledge base for a patient-facing health assistant.",
      "Implemented persistent patient memory with a hybrid MongoDB and vector store using semantically clustered embeddings.",
      "Built context-aware retrieval for nearby care recommendations, disease alerts, and personalized health guidance.",
    ],
    technologies: [
      "Python",
      "VLM",
      "Computer Vision",
      "FastAPI",
      "AWS EC2",
      "Nginx",
      "Docker",
      "MongoDB",
      "Vector DB",
      "RAG",
      "NLP",
      "LangChain",
    ],
  },
];
